### ISSUE TITLE
TypeError by use the sample flow

### ISSUE THREAD

**Issue by HubertusH** [bartbutenaers/node-red-contrib-tank-volume#1]
Hi,

i try to test yout tank-node first with your sample flow. By klick the inject node i get the error:
`TypeError: Cannot read property 'forEach' of undefined`

**Comment by bartbutenaers** [comment]
Evening @HubertusH,

Very kind of you to test this new node, before I publish it on NPM!!

Last week there was a [feature request](https://discourse.nodered.org/t/announce-node-red-contrib-tank-volume-beta/47101/31?u=bartbutenaers) to allow custom table tanks to be calculated.  Seems that feature introduced in bug for all the other types.  Damn, I should have tested that...

It should be _**fixed**_ now on Github, so if you please can install it again and let me know if it is solved.

BTW if you have any other problems, don't hesitate to let me know!
Bart

**Comment by HubertusH** [comment]
> Evening @HubertusH,
> 
> Very kind of you to test this new node, before I publish it on NPM!!
> 
> Last week there was a [feature request](https://discourse.nodered.org/t/announce-node-red-contrib-tank-volume-beta/47101/31?u=bartbutenaers) to allow custom table tanks to be calculated. Seems that feature introduced in bug for all the other types. Damn, I should have tested that...
> 
> It should be _**fixed**_ now on Github, so if you please can install it again and let me know if it is solved.
> 
> BTW if you have any other problems, don't hesitate to let me know!
> Bart

Thank you Bart, i have install it again and the error is gone!
Now i wait for my sensor to test the node ;-)

BR Hubertus

**Comment by bartbutenaers** [comment]
Closing due to long inactivity
