### ISSUE TITLE
Tank images not showing (unauthorized error)

### ISSUE THREAD

**Issue by mereshow** [bartbutenaers/node-red-contrib-tank-volume#2]
Hi,

I installed the node in a Node-RED instance running on Docker. When editing the node, I get an unauthorized error when it tries to retrieve the tank images:

![image](https://user-images.githubusercontent.com/4802386/140890422-9962653f-cc88-4b73-aa77-0bad2af7a1f5.png)

I inspected the node directory inside docker and the images permissions (at file system level) and everyone is allowed to read. I see nothing strange in the Node-RED settings. The only thing I changes in the settings (from default) is exposing the admin page in the "/admin" path and the dashboard in the root path "/" of my domain.

What do I have to look for to solve this?

**Comment by bartbutenaers** [comment]
Hey @mereshow,

Thanks for the clear description of the issue!
I was a bit surprised that it didn't work for you, so I have asked this [question](https://discourse.nodered.org/t/not-sure-how-to-deal-with-httpadminroot/53473/2?u=bartbutenaers) in the Node-RED forum.
Could you please check whether the proposed solution works:
1. Find your .../.node-red/node_modules/node-red-contrib-tank-volume/tank_volume.js file

2. At the bottom of that file remove the red underlined part:

   ![image](https://user-images.githubusercontent.com/14224149/141011365-dbae3efb-9af4-4b6d-9b9b-41f0afa1ffa1.png)

3. Save that file and restart Node-RED

4. Hopefully it now works ...

Bart

**Comment by mereshow** [comment]
> Hey @mereshow,
> 
> Thanks for the clear description of the issue! I was a bit surprised that it didn't work for you, so I have asked this [question](https://discourse.nodered.org/t/not-sure-how-to-deal-with-httpadminroot/53473/2?u=bartbutenaers) in the Node-RED forum. Could you please check whether the proposed solution works:
> 
> 1. Find your .../.node-red/node_modules/node-red-contrib-tank-volume/tank_volume.js file
> 2. At the bottom of that file remove the red underlined part:
>    ![image](https://user-images.githubusercontent.com/14224149/141011365-dbae3efb-9af4-4b6d-9b9b-41f0afa1ffa1.png)
> 3. Save that file and restart Node-RED
> 4. Hopefully it now works ...
> 
> Bart

That solves it! After changing the line and restarting the container the tank image is shown:

![image](https://user-images.githubusercontent.com/4802386/141086213-9e8692aa-c3f2-4ef3-97e7-0202067c0af7.png)

Thank you for the help, and for this node :+1:

**Comment by bartbutenaers** [comment]
@mereshow,
Thanks for the feedback!
The fix is now available in the pallette as version ***1.0.1***:

![image](https://user-images.githubusercontent.com/14224149/141371747-4c69159e-0494-4e6f-a47a-c6c19e70f5da.png)
