### ISSUE TITLE
no Issue - Request for a new Tank form

### ISSUE THREAD

**Issue by dremeier** [bartbutenaers/node-red-contrib-tank-volume#5]
would it be possible to add a calculation for this kind of Tank?

![image](https://user-images.githubusercontent.com/8443078/187249542-147b9d49-a011-488b-836d-6e6bd7b4490a.png)

**Comment by bartbutenaers** [comment]
Hi @dremeier,

I have nearly completed the calculations for those tanks.  Will try to update the documentation in the next days, so you can test it.

However I need to have a decent name for this type of tanks.  In many places (e.g. [here](https://www.calculatorsoup.com/calculators/construction/tank.php)) they call them ***oval tanks***, but I have oval tanks already in this node for another tank type.  So not sure how to call them ...

Bart

**Comment by dremeier** [comment]
Hi @bartbutenaers,
that sound very good.
This kind of tanks is called "Batterietank" in german. I don´t know if "battery tank" would be a decent name for it.

**Comment by bartbutenaers** [comment]
I think they call it battery tank, becaus you have a series of N identical tanks.  Like in a battery.  But this node only calculates a single of those tanks.  So need to know how these volumes are called...

**Comment by bartbutenaers** [comment]
I will go for the horizontal and vertical ***"stadium"*** tank.  Thanks to wikipedia (see [stadium](https://en.m.wikipedia.org/wiki/Stadium_(geometry)#:%7E:text=A%20stadium%20is%20a%20two,%2C%20obround%2C%20or%20sausage%20body) geometry).

The *"pill"* tank could be more self-explaining, but we already have a *"capsule"* tank.  Which might become confusing...

**Comment by dremeier** [comment]
very good, wiki is really very helpfull :-)
please let us know when you are ready with the stadium tank, I`ll test it.

**Comment by bartbutenaers** [comment]
Version 1.1.0 is available for testing.  Since it is not available on npm yet,  Therefore you need to install it from this Github repo.  After you have git installed, you can install this repo by executing following command (from within your .node-red folder!!!):
```
npm install bartbutenaers/node-red-contrib-tank-volume
```
After refreshing you flow editor browser screen, you should see the two "stadium" new tank types:

![stadium_tanks_demo](https://user-images.githubusercontent.com/14224149/187550912-dcc75cff-3613-4aa3-91ef-f41687c402e3.gif)

Would be nice if you could do some tests, e.g. by comparing my calculations with an online calculator.  For example [this](https://www.calculatorsoup.com/calculators/construction/tank.php) calculator offers a horizontal/vertical "oval" tank, which looks like our statium tank.  When you entire the tank dimension and the fluid height, you can calculate the total liters and liters filled:

![image](https://user-images.githubusercontent.com/14224149/187551261-5936c12c-1feb-4478-a6f2-dcb11c23b6ae.png)

You can compare those numbers with the one calculated via this node...

Note that you should do tests with all kind of measured heights: when only part of the bottom circle is filled, when it is filled somewhere until the rectangular part, and at the end if the tanks is filled until the upper half circle.

Note that you can set the parameters in the node's config screen, or inject the settings via the input message. 
Here is an example flow:

![image](https://user-images.githubusercontent.com/14224149/187552302-0f1590d1-99d1-40ff-9021-76936c8ce4ff.png)
```
[{"id":"fe6bdcd4d8bb26d3","type":"debug","z":"6063841c422bab25","name":"Volume","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":940,"y":1120,"wires":[]},{"id":"fd5241ec19ad8ac5","type":"inject","z":"6063841c422bab25","name":"Horizontal stadium","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"tankType\":\"horiz_stad\",\"width\":300,\"height\":100,\"length\":200,\"measuredHeight\":20}","payloadType":"json","x":530,"y":1120,"wires":[["79a8e5409d310365"]]},{"id":"79a8e5409d310365","type":"tank-volume","z":"6063841c422bab25","name":"","tankType":"none","inputField":"payload","outputField":"payload","measurement":"fluid","inputUnit1":"cm","inputUnit2":"l","outputUnit":"l","topLimit":0,"bottomLimit":0,"diameter":0,"length":0,"width":0,"height":0,"length2":0,"width2":0,"height2":0,"coneHeight":0,"cylinderHeight":0,"diameterTop":0,"diameterBottom":0,"customTable":[],"x":750,"y":1120,"wires":[["fe6bdcd4d8bb26d3"]]},{"id":"f02bbf975745d2f8","type":"inject","z":"6063841c422bab25","name":"Vertical stadium","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"tankType\":\"vert_stad\",\"width\":100,\"height\":300,\"length\":200,\"measuredHeight\":280}","payloadType":"json","x":520,"y":1180,"wires":[["79a8e5409d310365"]]},{"id":"557755e58d359c59","type":"debug","z":"6063841c422bab25","name":"Volume","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":940,"y":1300,"wires":[]},{"id":"d259c8493f0f8ecc","type":"inject","z":"6063841c422bab25","name":"Measured depth","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"20","payloadType":"num","x":520,"y":1300,"wires":[["20cde38e9079224f"]]},{"id":"20cde38e9079224f","type":"tank-volume","z":"6063841c422bab25","name":"","tankType":"horiz_stad","inputField":"payload","outputField":"payload","measurement":"fluid","inputUnit1":"cm","inputUnit2":"l","outputUnit":"l","topLimit":0,"bottomLimit":0,"diameter":0,"length":"200","width":"300","height":"100","length2":0,"width2":0,"height2":0,"coneHeight":0,"cylinderHeight":0,"diameterTop":0,"diameterBottom":0,"customTable":[],"x":750,"y":1300,"wires":[["557755e58d359c59"]]},{"id":"0bd9ceb998918e61","type":"debug","z":"6063841c422bab25","name":"Volume","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":940,"y":1360,"wires":[]},{"id":"39c3681f5605f2e6","type":"inject","z":"6063841c422bab25","name":"Measured depth","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"280","payloadType":"num","x":520,"y":1360,"wires":[["0320e98773032d8e"]]},{"id":"0320e98773032d8e","type":"tank-volume","z":"6063841c422bab25","name":"","tankType":"vert_stad","inputField":"payload","outputField":"payload","measurement":"fluid","inputUnit1":"cm","inputUnit2":"l","outputUnit":"l","topLimit":0,"bottomLimit":0,"diameter":0,"length":"200","width":"100","height":"300","length2":0,"width2":0,"height2":0,"coneHeight":0,"cylinderHeight":0,"diameterTop":0,"diameterBottom":0,"customTable":[],"x":740,"y":1360,"wires":[["0bd9ceb998918e61"]]},{"id":"648a9291737b05f7","type":"comment","z":"6063841c422bab25","name":"Configure via input messages","info":"","x":520,"y":1060,"wires":[]},{"id":"60f66115b578fd6c","type":"comment","z":"6063841c422bab25","name":"Configure via the node config screen's","info":"","x":550,"y":1240,"wires":[]}]
```

**Comment by dremeier** [comment]
That works fine! I´m very happy with this node.
Because the stadium tank comes often in a battery It could be helpful to have a multiplier of how many tanks you have. On the other hand it is easy to do that calculation by a function node.
Just as a thought, for the input units it would be nice to have mm instead of cm, so there is no need for a comma. makes it more simple?

**Comment by bartbutenaers** [comment]
1. I could add a multiplier, but then the config screen becomes more complex again.  Moreover some people will want to have the sum of all thanks while others want the result of a single tank, which means the output message will also become more complex.  Think you better apply a multiplier yourself.  

   Of course I could mention this on the readme page.  If you have a simple example flow, would be nice if your could share it so I can put it on the readme page...

2. The millimeters was an easy one:

   ![image](https://user-images.githubusercontent.com/14224149/187671437-081db0da-e092-4538-a28c-6ab5fb3a7844.png)

   Please install the node again from Github and test whether it is ok.  Note that both the tank dimensions and the measured depth need to be in mm!!

   I understand your requirement about the comma, but I don't see why you want to work in millimeters.  Because do you have a sensor that is more accurate than 1 cm?  My ultrasonic transducers are not that accurate, so for me the millimeter option is useless (which is why I had never added it to this node).

**Comment by dremeier** [comment]
the mm are not necessary but I think it is more easy to handle. My Sensor is a TOF VL53L1X and very accurate. Of course there is some noise so I calculate a mean of 10 measurements.

here is my complete node:
`[
    {
        "id": "0bd9ceb998918e61",
        "type": "debug",
        "z": "67608b91.9e7df4",
        "name": "Volume",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 920,
        "y": 1160,
        "wires": []
    },
    {
        "id": "0320e98773032d8e",
        "type": "tank-volume",
        "z": "67608b91.9e7df4",
        "name": "",
        "tankType": "vert_stad",
        "inputField": "payload",
        "outputField": "payload",
        "measurement": "fluid",
        "inputUnit1": "cm",
        "inputUnit2": "l",
        "outputUnit": "l",
        "topLimit": "10",
        "bottomLimit": "10",
        "diameter": 0,
        "length": "210",
        "width": "71.4",
        "height": "148",
        "length2": 0,
        "width2": 0,
        "height2": 0,
        "coneHeight": 0,
        "cylinderHeight": 0,
        "diameterTop": 0,
        "diameterBottom": 0,
        "customTable": [],
        "x": 740,
        "y": 1080,
        "wires": [
            [
                "0bd9ceb998918e61",
                "e0476fcecd2cf136"
            ]
        ]
    },
    {
        "id": "e0476fcecd2cf136",
        "type": "function",
        "z": "67608b91.9e7df4",
        "name": "",
        "func": "msg.payload = msg.payload.usableFilledVolume * 3; // extract the payload from the object\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1000,
        "y": 1080,
        "wires": [
            [
                "3899a10d5989322a",
                "e43901ffa782dd2c",
                "f2bd33b1bb29f6d2"
            ]
        ]
    },
    {
        "id": "3899a10d5989322a",
        "type": "debug",
        "z": "67608b91.9e7df4",
        "name": "Splitt",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 1230,
        "y": 1200,
        "wires": []
    },
    {
        "id": "a6f1c098085364c1",
        "type": "ioBroker in",
        "z": "67608b91.9e7df4",
        "name": "VL53L1X_Distance-Tank",
        "topic": "sonoff.0.Oel-Tank.VL53L1X_Distance",
        "payloadType": "value",
        "onlyack": "",
        "func": "all",
        "gap": "",
        "fireOnStart": "false",
        "x": 270,
        "y": 1080,
        "wires": [
            [
                "0402ab74b1d2288a"
            ]
        ]
    },
    {
        "id": "0402ab74b1d2288a",
        "type": "smooth",
        "z": "67608b91.9e7df4",
        "name": "Quersumme bilden",
        "property": "payload",
        "action": "mean",
        "count": "4",
        "round": "",
        "mult": "single",
        "reduce": false,
        "x": 370,
        "y": 1160,
        "wires": [
            [
                "eaca623dce4cc093"
            ]
        ]
    },
    {
        "id": "551355b4e40a6219",
        "type": "debug",
        "z": "67608b91.9e7df4",
        "name": "Sensor fullstand in cm",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 680,
        "y": 1280,
        "wires": []
    },
    {
        "id": "eaca623dce4cc093",
        "type": "function",
        "z": "67608b91.9e7df4",
        "name": "",
        "func": "msg.payload = (Math.round(1460-msg.payload))/10;\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 520,
        "y": 1080,
        "wires": [
            [
                "0320e98773032d8e",
                "551355b4e40a6219",
                "9dbfb272ee546118",
                "153b4e76c352adf2"
            ]
        ]
    },
    {
        "id": "9dbfb272ee546118",
        "type": "ui_text",
        "z": "67608b91.9e7df4",
        "group": "a61b5e71.64287",
        "order": 2,
        "width": 0,
        "height": 0,
        "name": "",
        "label": "Füllstand",
        "format": "{{msg.payload}} cm",
        "layout": "row-left",
        "className": "",
        "x": 720,
        "y": 1160,
        "wires": []
    },
    {
        "id": "e43901ffa782dd2c",
        "type": "ui_text",
        "z": "67608b91.9e7df4",
        "group": "a61b5e71.64287",
        "order": 2,
        "width": 0,
        "height": 0,
        "name": "",
        "label": "Heizöl Tankinhalt",
        "format": "{{msg.payload}} Liter",
        "layout": "row-left",
        "className": "",
        "x": 1270,
        "y": 1080,
        "wires": []
    },
    {
        "id": "f2bd33b1bb29f6d2",
        "type": "ioBroker out",
        "z": "67608b91.9e7df4",
        "name": "schreib in Heizöl_Füllstand",
        "topic": "0_userdata.0.Öl-Heizung.HeizÖl_Tank",
        "ack": "true",
        "autoCreate": "false",
        "stateName": "",
        "role": "",
        "payloadType": "",
        "readonly": "",
        "stateUnit": "",
        "stateMin": "",
        "stateMax": "",
        "x": 1300,
        "y": 1140,
        "wires": []
    },
    {
        "id": "153b4e76c352adf2",
        "type": "ioBroker out",
        "z": "67608b91.9e7df4",
        "name": "schreib in Öl-Tank_fullstand",
        "topic": "0_userdata.0.Öl-Heizung.Öl-Tank_fullstand",
        "ack": "true",
        "autoCreate": "false",
        "stateName": "",
        "role": "",
        "payloadType": "",
        "readonly": "",
        "stateUnit": "",
        "stateMin": "",
        "stateMax": "",
        "x": 740,
        "y": 1220,
        "wires": []
    },
    {
        "id": "a61b5e71.64287",
        "type": "ui_group",
        "name": "Öl-Lager",
        "tab": "fc2fa63a.959978",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": false
    },
    {
        "id": "fc2fa63a.959978",
        "type": "ui_tab",
        "name": "ÖL-Heizung",
        "icon": "dashboard",
        "order": 3,
        "disabled": false,
        "hidden": false
    }
]`

Here is an example to extract one item from the object and multiply it 3 times:

`[
    {
        "id": "03eab8984ca0b78f",
        "type": "tank-volume",
        "z": "67608b91.9e7df4",
        "name": "",
        "tankType": "vert_stad",
        "inputField": "payload",
        "outputField": "payload",
        "measurement": "fluid",
        "inputUnit1": "cm",
        "inputUnit2": "l",
        "outputUnit": "l",
        "topLimit": "10",
        "bottomLimit": "10",
        "diameter": 0,
        "length": "210",
        "width": "71.4",
        "height": "148",
        "length2": 0,
        "width2": 0,
        "height2": 0,
        "coneHeight": 0,
        "cylinderHeight": 0,
        "diameterTop": 0,
        "diameterBottom": 0,
        "customTable": [],
        "x": 640,
        "y": 1500,
        "wires": [
            [
                "a1a0d479c57ca3c4",
                "d12e7ccddc3da34e"
            ]
        ]
    },
    {
        "id": "a1a0d479c57ca3c4",
        "type": "debug",
        "z": "67608b91.9e7df4",
        "name": "Volume",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 820,
        "y": 1580,
        "wires": []
    },
    {
        "id": "d12e7ccddc3da34e",
        "type": "function",
        "z": "67608b91.9e7df4",
        "name": "",
        "func": "msg.payload = msg.payload.usableFilledVolume * 3; // extract the payload from the object\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 900,
        "y": 1500,
        "wires": [
            [
                "0c9f41fea013eeee"
            ]
        ]
    },
    {
        "id": "0c9f41fea013eeee",
        "type": "debug",
        "z": "67608b91.9e7df4",
        "name": "Splitt",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 1090,
        "y": 1580,
        "wires": []
    },
    {
        "id": "432e5bbbdc68600a",
        "type": "inject",
        "z": "67608b91.9e7df4",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "60",
        "payloadType": "num",
        "x": 390,
        "y": 1500,
        "wires": [
            [
                "03eab8984ca0b78f"
            ]
        ]
    }
]`

will try the mm later....

**Comment by bartbutenaers** [comment]
I have added a [tank battery](https://github.com/bartbutenaers/node-red-contrib-tank-volume/blob/main/README.md#tank-battery) section on the readme page.  Hopefully you don't mind that I have added your picture?  Have tried to find another one on the web, but couldn't find one (for domestic usage)...

**Comment by dremeier** [comment]
That is absolutely fine to use my pic. 
like to thank you very much for your work, it was very helpful for me.

**Comment by bartbutenaers** [comment]
Ok thanks!
As soon as you have tested the mm, I will publish it on npm

**Comment by dremeier** [comment]
as expected, the mm version works like the other versions very well :-)

**Comment by bartbutenaers** [comment]
@dremeier,
Thanks for thinking out loud, and for testing!
Version ***1.1.0*** is now available in the palette:

![image](https://user-images.githubusercontent.com/14224149/188236740-140fac37-b2b2-44b8-bdb9-324cf4c1a027.png)
